import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html", host: "localhost" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the protected branded dashboard experience", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<html[^>]+lang="pt-BR"/i);
  assert.match(html, /<title>DASH BOARD - MONITORAMENTO DE COLETA<\/title>/i);
  assert.match(html, /J&amp;T Express/);
  assert.match(html, /Acesso ao dashboard/);
  assert.match(html, /Entre para visualizar os indicadores da sua regional/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton|Your site is taking shape/i);
});

test("persists the latest workbook and exposes all requested filters", async () => {
  const source = await readFile(new URL("../app/dashboard-app.tsx", import.meta.url), "utf8");
  const route = await readFile(new URL("../app/api/workbook/route.ts", import.meta.url), "utf8");
  const parser = await readFile(new URL("../app/lib/workbook.ts", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const hosting = await readFile(new URL("../.openai/hosting.json", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const i18n = await readFile(new URL("../app/lib/i18n.ts", import.meta.url), "utf8");

  assert.match(source, /import\("\.\/lib\/workbook"\)/);
  assert.match(source, /fetch\("\/api\/workbook"/);
  assert.match(source, /Última atualização/);
  assert.match(source, /formatDateTime/);
  assert.match(route, /dashboard_state/);
  assert.match(route, /WORKBOOKS/);
  assert.match(route, /function streamWorkbookPayload/);
  assert.match(route, /body\.pipeThrough\(new TransformStream/);
  assert.match(route, /return streamWorkbookPayload\(object\.body, row\.fileName, row\.updatedAt\)/);
  assert.match(route, /LATEST_OBJECT_KEY/);
  assert.match(route, /movement-latest\.json/);
  assert.match(route, /seller-list-latest\.json/);
  assert.match(route, /seller-performance-latest\.json/);
  assert.match(route, /bipagem-latest\.json/);
  assert.match(route, /ON CONFLICT\(id\) DO UPDATE/);
  assert.match(source, /id="taxa-upload"[\s\S]*?multiple/);
  assert.match(source, /mergeHistory: true/);
  assert.match(source, /Histórico atualizado/);
  assert.match(source, /taxaRegionalPoc/);
  assert.doesNotMatch(source, /function taxaMaximumEndDate/);
  assert.match(source, /filter\(\(date\) => date >= taxaDateStart && date <= taxaDateEnd\)[\s\S]*?slice\(-TAXA_MAX_PERIOD_DAYS\)/);
  assert.match(source, /setTaxaDateEnd\(data\.initialEnd\)/);
  assert.match(source, /const taxaDailyPeriod = useMemo/);
  assert.match(source, /const points = taxaDailyPeriod\.map/);
  assert.match(source, /Taxa de coleta com tentativa por regional — período selecionado/);
  assert.match(source, /className="dashboard-data-table taxa-poc-table taxa-poc-regional-rgm-table"/);
  assert.match(source, /Taxa com tentativa por RM — período selecionado/);
  assert.match(source, /const responsibility = responsibilityForBase\(responsibilityLoaded, record\.base\)/);
  assert.doesNotMatch(source, /showTaxaRmPoc/);
  assert.match(source, /className="dashboard-data-table taxa-poc-table taxa-poc-rm-table"/);
  assert.match(source, /label=\{t\("Região do RM"\)\}/);
  assert.match(source, /taxaSelectedRmAreas\.has\(rmAreaForBase\(responsibilityLoaded, record\.base\)\)/);
  assert.match(source, /<th>\{t\("Região do RM"\)\}<\/th>/);
  assert.match(source, /<th>\{t\("Responsável do RM"\)\}<\/th>/);
  assert.ok((source.match(/<th>RGM<\/th>/g) ?? []).length >= 2);
  assert.match(source, /attemptRateTargetForOrigins/);
  assert.match(source, /origin\.includes\("tiktok"\)\) return 0\.98/);
  assert.match(source, /origin\.includes\("temu"\)\) return 0\.99/);
  assert.match(source, /taxaAttemptTarget == null \? null : <th className="taxa-poc-target-header">\{t\("Meta"\)\}<\/th>/);
  assert.match(source, /<th>RGM<\/th>[\s\S]*?taxa-poc-target-header[\s\S]*?taxaRegionalPoc\.dates\.map/);
  assert.match(source, /downloadTaxaManagementExcel/);
  assert.match(source, /formatTaxaExcelPeriod\(periodStart, periodEnd\)/);
  assert.match(source, /summary: summarizeTaxaPeriod\(records\)/);
  assert.match(source, /row\.summary\.onTimeRate/);
  assert.match(source, /row\.summary\.collectionWithAttemptsRate/);
  assert.match(source, /row\.toCollect > 0 \? row\.onTimeRate : null/);
  assert.match(source, /row\.toCollect > 0 \? row\.attemptRate : null/);
  assert.match(source, /taxaSummary\.onTimeRate/);
  assert.match(source, /taxaSummary\.collectionWithAttemptsRate/);
  assert.match(source, /Taxa de coleta\\n揽收及时率/);
  assert.match(source, /Taxa com tentativa\\n尝试揽收率/);
  assert.match(source, /RGM\\n区域负责人/);
  assert.match(source, /Meta\\n目标/);
  assert.match(styles, /\.taxa-poc-table td\.target-cell strong\s*\{[\s\S]*?color: #15803d/);
  assert.equal((source.match(/dashboard-data-table/g) ?? []).length, 14);
  assert.match(styles, /--table-header: #e60000/);
  assert.match(styles, /\.dashboard-data-table thead th\s*\{[\s\S]*?background: var\(--table-header\)/);
  assert.match(styles, /\.dashboard-data-table tbody tr:nth-child\(even\)/);
  assert.match(styles, /\.dashboard-data-table tfoot th/);
  assert.match(styles, /@media print[\s\S]*?\.dashboard-data-table thead th/);
  assert.match(source, /percentual do último dia determina o ranking do maior para o menor/);
  assert.match(source, /const aLatest = a\.values\.at\(-1\)/);
  assert.match(source, /const bLatest = b\.values\.at\(-1\)/);
  assert.match(source, /bLatest\.rate - aLatest\.rate/);
  assert.match(source, /latestPerformanceDate = taxaRegionalPoc\.dates\.at\(-1\)/);
  assert.match(source, /b\.latestAttemptRate - a\.latestAttemptRate/);
  assert.match(source, /totalOrders: values\.reduce\(\(sum, value\) => sum \+ value\.orders, 0\)/);
  assert.equal((source.match(/<th>\{t\("Total de pedidos"\)\}<\/th>/g) ?? []).length, 2);
  assert.match(source, /taxaRegionalPoc\.totalOrders/);
  assert.match(source, /downloadTaxaRegionalPocExcel/);
  assert.match(source, /taxa_de_coleta_gerencial_/);
  assert.match(source, /taxaRmPoc\.totalOrders/);
  assert.match(source, /row\.totalOrders > 0 \|\| row\.values\.some\(\(value\) => value\.toCollect > 0\)/);
  assert.match(source, /total: taxaRegionalPoc\.total, totalOrders: taxaRegionalPoc\.totalOrders/);
  assert.match(source, /Total de pedidos\\n总订单量/);
  assert.match(styles, /\.taxa-poc-orders-column\s*\{[\s\S]*?width: 92px/);
  assert.equal((source.match(/taxa-poc-date-header/g) ?? []).length, 2);
  assert.match(styles, /\.taxa-poc-table thead th\.taxa-poc-date-header\s*\{[\s\S]*?position: sticky[\s\S]*?text-align: center !important/);
  assert.match(styles, /\.taxa-poc-day-column\s*\{[\s\S]*?width: 84px/);
  assert.match(styles, /@media print[\s\S]*?\.taxa-poc-table-wrap,[\s\S]*?overflow: visible !important/);
  assert.match(source, /const records = taxaFilteredRecords/);
  assert.match(source, /\[taxaDateEnd, taxaDateStart, taxaFilteredRecords, taxaLoaded\]/);
  assert.match(source, /record\.date >= taxaDateStart/);
  assert.match(source, /record\.date <= taxaDateEnd/);
  assert.match(source, /taxaPocTrend/);
  assert.match(source, /Resultado geral do período selecionado/);
  assert.match(source, /className="taxa-poc-line-chart"/);
  assert.match(styles, /\.taxa-poc-table-wrap\s*\{[\s\S]*?max-height: 430px/);
  assert.match(styles, /\.taxa-poc-table td strong\s*\{[\s\S]*?font-size: 11px/);
  assert.match(styles, /\.taxa-poc-table\s*\{[\s\S]*?table-layout: fixed/);
  assert.match(styles, /\.taxa-poc-region-column\s*\{[\s\S]*?width: 68px/);
  assert.match(styles, /\.taxa-poc-rm-area-column,[\s\S]*?width: 108px/);
  assert.match(styles, /\.taxa-poc-rm-name-column,[\s\S]*?width: 170px/);
  assert.match(styles, /\.taxa-poc-rgm-column\s*\{[\s\S]*?width: 190px/);
  assert.match(styles, /\.taxa-poc-regional-rgm-table thead tr > :nth-child\(2\),[\s\S]*?position: sticky/);
  assert.match(styles, /\.taxa-poc-rm-table thead tr > :nth-child\(2\),[\s\S]*?left: 108px/);
  assert.match(styles, /\.taxa-poc-rm-table thead tr > :nth-child\(3\),[\s\S]*?left: 278px/);
  assert.match(styles, /@media print[\s\S]*?\.taxa-poc-table\s*\{[\s\S]*?table-layout: fixed/);
  assert.match(source, /taxaGeneralMonthlyTrend/);
  assert.doesNotMatch(source, /taxaGeneralWeeklyTrend/);
  assert.match(source, /Taxa de coleta x taxa com tentativa/);
  assert.match(source, /Evolução mensal geral/);
  assert.match(source, /general-rate-line collection/);
  assert.match(source, /general-rate-line attempt/);
  assert.match(source, /formatWeekday\(date\)/);
  assert.match(source, /isWeekendDate\(date\)/);
  assert.match(source, /monitoringSummaryDates = periodDates/);
  assert.match(source, /monitoringMetricsForRow\(row, \[\.\.\.selectedStatuses\]\)/);
  assert.match(source, /for \(const status of loaded\.statuses\)/);
  assert.match(source, /\.\.\.displayedMetrics\.map\(\(metric\) => t\(metric\)\)/);
  assert.match(source, /downloadTaxaManagementExcel\([\s\S]*?monitoramento_bases_/);
  assert.match(source, /label=\{t\("Previsto a coletar"\)\}[\s\S]*?monitoringSummaryMetrics\.orderVolume/);
  assert.match(source, /label=\{t\("Aguardando coleta"\)\}[\s\S]*?monitoringSummaryMetrics\.awaiting/);
  assert.match(source, /label=\{t\("Taxa de coleta"\)\}[\s\S]*?monitoringCollectionRate\(monitoringSummaryMetrics\)/);
  assert.match(source, /label=\{t\("Taxa de pedidos aguardando coleta"\)\}[\s\S]*?monitoringAwaitingRate\(monitoringSummaryMetrics\)/);
  assert.match(source, /monitoringMetricForStatus[\s\S]*?coleta prevista pick up[\s\S]*?aguardando coleta pick up[\s\S]*?status atual coletado[\s\S]*?status atual recebido na base[\s\S]*?status atual chegou ao sc/);
  assert.match(source, /"pick up应揽收": "Coleta prevista Pick-up"/);
  assert.match(source, /"pick up待揽收": "Aguardando coleta Pick-up"/);
  assert.match(source, /attempt-weekday-label.*is-weekend/);
  assert.match(source, /general-rate-value-label collection/);
  assert.match(source, /general-rate-value-label attempt/);
  assert.doesNotMatch(source, /taxa-monthly-regional-section/);
  assert.doesNotMatch(source, /Taxa com tentativa por regional/);
  assert.doesNotMatch(source, /TOP 6 bases abaixo de 92% que puxam a média/);
  assert.doesNotMatch(source, /taxaCriticalBases/);
  assert.match(source, /taxaSelectedRegions\.size === taxaRegionOptions\.length[\s\S]*?Todas as regionais/);
  assert.match(source, /taxa-poc-rm-block taxa-poc-rm-replacement/);
  assert.match(source, /downloadTaxaRmPocExcel/);
  assert.match(source, /name: "RM"/);
  assert.match(source, /taxaGeneralTrendPanel/);
  assert.match(source, /taxaPocTrend\.points[\s\S]*?taxaGeneralTrendPanel[\s\S]*?<\/article>/);
  assert.match(styles, /\.taxa-poc-rm-replacement \.taxa-poc-rm-table-wrap\s*\{[\s\S]*?max-height: 720px/);
  assert.match(styles, /\.taxa-general-aligned-panel \.general-rate-line-chart svg\s*\{[\s\S]*?aspect-ratio: 700 \/ 180/);
  assert.match(source, /formatRate\(point\.collectionRate\)/);
  assert.match(source, /formatRate\(point\.attemptRate\)/);
  assert.match(source, /formatRate\(point\.rate\)/);
  assert.match(styles, /\.filter-grid\s*\{[\s\S]*?repeat\(6, minmax\(0, 1fr\)\)/);
  assert.match(styles, /\.movement-filter-grid\s*\{[\s\S]*?repeat\(auto-fit, minmax\(180px, 1fr\)\)/);
  assert.match(styles, /\.sellers-filter-grid\s*\{[\s\S]*?repeat\(8, minmax\(0, 1fr\)\)/);
  assert.match(styles, /\.filter-grid \.multi-select summary,[\s\S]*?height: 40px;[\s\S]*?border-radius: 8px;/);
  assert.match(source, /downloadTaxaTableExcel/);
  assert.match(source, /downloadMonitoringTableExcel/);
  assert.match(source, /downloadMovementTableExcel/);
  assert.match(source, /downloadSellerTableExcel/);
  assert.match(source, /header: "RM", value: \(row\) => row\.rmLabel/);
  assert.match(source, /<th>RM<\/th>/);
  assert.match(source, /<td>\{row\.rmLabel\}<\/td>/);
  assert.match(source, /downloadRowsAsExcel/);
  assert.match(source, /XLSX\.utils\.aoa_to_sheet/);
  assert.match(source, /XLSX\.writeFile/);
  assert.match(source, /Baixar Excel/);
  assert.equal((source.match(/className="table-download-button/g) ?? []).length, 14);
  assert.match(source, /downloadSellerRegionalPerformanceExcel/);
  assert.match(source, /formatSellerExcelPeriod\(sellerDateStart, sellerDateEnd\)/);
  assert.match(source, /J&T重点保障及单商多服监控/);
  assert.match(source, /区域（Regional）/);
  assert.match(source, /网点（Base）/);
  assert.match(source, /Aguardando coleta\\n待揽收订单量/);
  assert.match(source, /totalMergeEndColumn: 2/);
  assert.match(source, /header: "RGM", value: \(row\) => row\.rgmLabel/);
  assert.match(source, /officialRgmForRegion\(row\.region\)/);
  assert.match(source, /responsibilityForBase\(responsibilityLoaded, row\.base\)\.rgm/);
  assert.match(source, /kind: "bipagem"/);
  assert.match(source, /buildBipagemLoadedData/);
  assert.match(source, /bipagemSelectedRegions/);
  assert.match(source, /bipagemSelectedRms/);
  assert.match(source, /bipagemSelectedBases/);
  assert.match(source, /bipagemSelectedOrigins/);
  assert.match(source, /Falta de bipagem por regional/);
  assert.match(source, /Falta de bipagem por base e RM/);
  assert.match(styles, /\.dashboard-data-table\.bipagem-summary-table thead th,[\s\S]*?height: 30px/);
  assert.match(styles, /\.bipagem-regional-card,[\s\S]*?\.bipagem-detail-card\s*\{[\s\S]*?width: 100%/);
  assert.match(styles, /\.dashboard-data-table\.bipagem-summary-table tbody td,[\s\S]*?min-height: 28px/);
  assert.match(styles, /\.bipagem-summary-table th:nth-child\(2\) \{ width: 15%/);
  assert.match(styles, /\.bipagem-detail-table th:nth-child\(4\) \{ width: 13%/);
  assert.match(styles, /\.bipagem-detail-table th:nth-child\(12\) \{ width: 10%/);
  assert.match(source, /Tipo de problema/);
  assert.match(source, /bipagemProblemType/);
  assert.match(source, /bipagemScannedForProblem/);
  assert.match(source, /bipagemMissingForProblem/);
  assert.match(source, /Comparativo/);
  assert.match(source, /BipagemComparisonCell/);
  assert.match(source, /downloadBipagemRegionalExcel/);
  assert.match(source, /downloadBipagemBaseExcel/);
  assert.match(source, /index % 2 === 0 \? 7 : 14/);
  assert.match(route, /mergeTaxaHistory/);
  assert.match(route, /payload\.mergeHistory/);
  assert.doesNotMatch(source, /label=\{t\("Bases com movimento"\)\}/);
  assert.match(hosting, /"d1":\s*"DB"/);
  assert.match(hosting, /"r2":\s*"WORKBOOKS"/);
  assert.match(source, /label=\{t\("Regional"\)\}/);
  assert.match(source, /label=\{t\("Base"\)\}/);
  assert.match(source, /basesForRegions/);
  assert.doesNotMatch(source, /topBasesForRegions/);
  assert.match(source, /ConsolidatedBaseRow/);
  assert.match(source, /Datas consolidadas no período/);
  assert.match(source, /b\.total - a\.total/);
  assert.match(source, /recebido na base/);
  assert.match(source, /expedida pela base/);
  assert.match(source, /em transito a partir da base/);
  assert.match(source, /Data inicial/);
  assert.match(source, /Data final/);
  assert.match(source, /label=\{t\("Status"\)\}/);
  assert.match(source, /kind: "movement"/);
  assert.match(source, /buildMovementLoadedData/);
  assert.match(source, /movementRegionalOver2Summary/);
  assert.match(source, /movementRmOver2Summary/);
  assert.match(styles, /\.monitoring-summary-grid\s*\{[\s\S]*?grid-template-columns: minmax\(0, 1fr\)/);
  assert.match(styles, /\.monitoring-summary-table th,[\s\S]*?overflow-wrap: anywhere;[\s\S]*?white-space: normal/);
  assert.match(styles, /\.movement-rm-summary-table\.monitoring-summary-table th:nth-child\(1\)\s*\{[\s\S]*?width: 13%/);
  assert.match(styles, /\.movement-rm-summary-table\.monitoring-summary-table th:nth-child\(5\)\s*\{[\s\S]*?width: 9%/);
  assert.match(source, /function movementFrom2DaysTotal\(record: MovementRecord\)/);
  assert.match(source, /record\.over2Days \+/);
  assert.match(source, /record\.over30Days/);
  assert.match(source, /Sem movimentação por regional/);
  assert.match(source, /Sem movimentação por RM/);
  assert.match(source, /downloadMovementRegionalOver2Excel/);
  assert.match(source, /downloadMovementRmOver2Excel/);
  const movementMetrics = await readFile(new URL("../app/lib/movement-summary.ts", import.meta.url), "utf8");
  assert.match(movementMetrics, /Total há 2 dias ou mais/);
  assert.match(source, /MOVEMENT_SUMMARY_METRICS\.map/);
  assert.doesNotMatch(source, /TOP 10 sem movimentação há mais de 2 dias/);
  assert.doesNotMatch(source, /Composição por tempo sem movimento/);
  assert.doesNotMatch(source, /Movimentação por regional/);
  assert.match(source, /movementBasesForRegions/);
  assert.match(source, /kind: "sellerList"/);
  assert.match(source, /kind: "sellerSpecialList"/);
  assert.doesNotMatch(source, /id="seller-special-filter"/);
  assert.match(route, /seller-special-list-latest\.json/);
  assert.match(source, /kind: "sellerPerformance"/);
  assert.match(source, /buildSellerReferenceData/);
  assert.match(source, /buildSellerPerformanceData/);
  assert.match(source, /preferredSheetName: "SELLERS"/);
  assert.match(source, /重点保障商家类型/);
  assert.match(source, /Id Seller\/remetente/);
  assert.match(source, /Status atual – Aguardando coleta/);
  assert.match(source, /当前状态-网点发件流程中/);
  assert.doesNotMatch(source, /TOP 10 sellers T5 por volumetria/);
  assert.match(source, /Relatório diário \{categories\}/);
  assert.match(source, /summarizeAwaitingByBaseAndRm\(sellerFilteredRecords\)/);
  assert.match(source, /Aguardando coleta por base e RM/);
  assert.match(source, /Pedidos aguardando coleta/);
  assert.match(source, /seller-rm-awaiting-table-wrap/);
  assert.match(source, /downloadSellerRmAwaitingExcel/);
  assert.match(source, /aguardando_coleta_por_base_rm_/);
  assert.match(source, /seller-rm-download-button/);
  assert.match(source, /Volume de pedidos\\n总订单量/);
  assert.match(source, /Taxa de coleta\\n揽收率 %/);
  assert.match(source, /percentageColumns: \[6\]/);
  assert.match(source, /Composição \{categories\}/);
  assert.match(source, /SELLER_CATEGORIES = \["J&T 重点保障", "单商多服"\]/);
  assert.match(source, /normalizeSellerCategory\(row\[tierColumn\]\)/);
  assert.match(source, /Lista oficial de sellers/);
  assert.doesNotMatch(source, /Relatório diário T4\/T5 por regional/);
  assert.match(source, /seller-date-start/);
  assert.match(source, /seller-date-end/);
  assert.match(source, /sellerRegionalPerformance/);
  assert.match(styles, /\.seller-regional-table\s*\{[\s\S]*?table-layout: fixed/);
  assert.match(styles, /\.seller-regional-table th,[\s\S]*?height: 32px;[\s\S]*?padding: 6px 9px/);
  assert.match(source, /Volume coletado/);
  assert.match(source, /secondaryLabel=\{t\("Volume coletado"\)\}/);
  assert.match(source, /% Taxa de coleta/);
  assert.match(source, /SELLER_REGIONAL_RATE_TARGET = 0\.98/);
  assert.match(source, /right\.rate - left\.rate/);
  assert.match(source, /aria-sort="descending"/);
  assert.match(source, /is-on-target/);
  assert.match(source, /is-below-target/);
  assert.match(source, /Total geral/);
  assert.doesNotMatch(source, /TOP 10 sellers abaixo de 90%/);
  assert.match(source, /TOP 10 sellers com pedidos sem coleta/);
  assert.match(source, /row\.awaiting > 0 && row\.processed === 0/);
  assert.match(source, /right\.awaiting - left\.awaiting/);
  assert.match(source, /Resultado dos sellers/);
  assert.match(source, /SELLER_OUTCOME_LABELS/);
  assert.match(source, /aria-controls="seller-detail-section"/);
  assert.match(source, /sortSellerReportRowsByAwaiting/);
  assert.match(source, /aria-sort="descending"/);
  assert.match(source, /className="language-selector"/);
  assert.match(source, /Autorizar envio de Excel/);
  assert.match(source, /\/api\/upload-auth/);
  assert.match(route, /isUploadAuthorized/);
  assert.match(route, /if \(!uploadSecretsConfigured\(\)\)/);
  assert.match(source, /DASHBOARD_LANGUAGES\.map/);
  assert.match(source, /document\.documentElement\.lang\s*=\s*dashboardHtmlLang/);
  assert.match(source, /MODULE_IMPORT_FAILURE_PATTERN/);
  assert.match(source, /recoverFromStaleModuleImport\(cause\)/);
  assert.match(source, /window\.location\.replace\(reloadUrl\.toString\(\)\)/);
  assert.match(source, /now - lastReload < 60_000/);
  assert.match(i18n, /code:\s*"pt"[\s\S]*htmlLang:\s*"pt-BR"/);
  assert.match(i18n, /code:\s*"en"[\s\S]*htmlLang:\s*"en"/);
  assert.match(i18n, /code:\s*"zh"[\s\S]*htmlLang:\s*"zh-CN"/);
  assert.match(styles, /\.language-selector select/);
  assert.match(styles, /#seller-detail-heading[\s\S]*scroll-margin-top/);
  assert.match(source, /sellerBasesForRegions/);
  assert.match(source, /safeRate\(processed, total\)/);
  assert.match(source, /toCollect: rawToCollect/);
  assert.match(source, /summarizeTaxaPeriod\(taxaFilteredRecords\)/);
  assert.match(source, /label=\{t\("Taxa de coleta"\)\}[\s\S]*?value=\{formatRate\(taxaSummary\.onTimeRate\)\}[\s\S]*?taxaSummary\.onTime/);
  assert.match(source, /label=\{t\("Previsto a coletar"\)\}[\s\S]*?taxaSummary\.toCollect/);
  assert.match(source, /label=\{t\("Aguardando coleta"\)\}[\s\S]*?taxaSummary\.notCollected/);
  assert.match(source, /Taxa de pedidos aguardando coleta/);
  assert.match(source, /current\.onTime \+= record\.onTime/);
  assert.match(source, /collectionRate: safeRate\(month\.onTime, month\.toCollect\)/);
  assert.match(source, /<th>\{t\("Taxa de coleta"\)\}<\/th>[\s\S]*?formatRate\(row\.onTimeRate\)/);
  assert.match(source, /Gerar PDF/);
  assert.match(source, /Relatório gerado em/);
  assert.match(source, /window\.print/);
  assert.match(source, /Indicadores do período/);
  assert.doesNotMatch(source, /<h2>\{t\("Tendência diária"\)\}<\/h2>/);
  assert.doesNotMatch(source, /<h2>\{t\("Composição por status"\)\}<\/h2>/);
  assert.match(source, /monitoringRegionalSummary/);
  assert.match(source, /monitoringRmSummary/);
  assert.match(source, /downloadMonitoringRegionalSummaryExcel/);
  assert.match(source, /downloadMonitoringRmSummaryExcel/);
  assert.match(source, /Taxa de pedidos aguardando coleta/);
  assert.match(source, /MONITORING_STATUS_LABELS/);
  assert.match(source, /options=\{\[\.\.\.MONITORING_METRIC_OPTIONS\]\}/);
  assert.match(source, /selectedOrigins\.has\(origin\)/);
  assert.match(source, /monitoring-filter-grid/);
  assert.match(source, /Total por regional/);
  assert.match(source, /Dados por base/);
  assert.match(source, /screen-table-body/);
  assert.match(source, /print-table-body/);
  assert.match(styles, /size:\s*A4 portrait/);
  assert.match(styles, /\.brand-header[\s\S]*position:\s*static/);
  assert.match(styles, /\.filters-card[\s\S]*display:\s*block !important/);
  assert.match(styles, /\.screen-table-body[\s\S]*display:\s*none/);
  assert.match(styles, /\.print-table-body[\s\S]*display:\s*table-row-group/);
  assert.match(source, /slice\(-5\)/);
  assert.match(source, /EmptyDashboardPanel/);
  assert.doesNotMatch(source, /UploadPanel|<main className=\{loaded \? "dashboard-main" : "landing-main"\}/);
  assert.match(parser, /pdd de saída/i);
  assert.match(parser, /statusColumns/);
  assert.match(layout, /og\.png/);
  assert.match(source, /localStorage\.setItem\(DASHBOARD_LANGUAGE_STORAGE_KEY/);
  assert.doesNotMatch(source, /XMLHttpRequest/);
  assert.match(source, /sessionStorage/);
  assert.match(source, /\/api\/view-auth/);
  assert.match(route, /filterWorkbookForRegion/);
});
